#!/usr/bin/env bash
# get information about subdomain and its destination IP

get_Arecord () {
    Arec=$(dig "$2"."$1" | grep -A1 'ANSWER SECTION:' | awk 'FNR == 2 {print $5}')
    echo "The subdomain $2 is a A record and points to $Arec"
}

if [ "$2" ]
then
    get_Arecord "$1" "$2"
else
    get_Arecord "$1" "www"
    get_Arecord "$1" "lb-01"
    get_Arecord "$1" "web-01"
    get_Arecord "$1" "web-02"
fi
