#!/usr/bin/env bash
# script that copy a local file to a server in home directory
#
# Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY
# PATH_TO_FILE: Is the path of file in local machine ($1)
# IP: server ($2)
# USERNAME: user to access ($3)
# PATH_TO_SSH_KEY: Is the path of the ssh key to be used with -i flag ($4)
# There is not destination path by input. The destination will be: ~/

if [ "$#" -lt 3 ]
then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
    scp -i "$4" -o StrictHostKeyChecking=no "$1" "$3@$2:~/"
fi
