#!/usr/bin/env bash
# Script that install nginx web server and open port 80
apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo "Holberton School for the win!" > /var/www/html/index.html
