#!/usr/bin/env bash
# Enable port 80 in nginx web server
sed -i "s/listen 8080 default_server;/listen 80 default_server;/" /etc/nginx/sites-enabled/default
# sudo pkill -f nginx & wait $!
service nginx restart
