#!/usr/bin/env bash
# Process and PID file
echo $$ > /var/run/holbertonscript.pid
i=0
while [ $i -le 2 ]
do
    echo To infinity and beyond
    sleep 2
    trap 'echo I hate the kill command; exit' SIGTERM
    trap 'echo Y U no love me?!' SIGINT
    trap 'rm /var/run/holbertonscript.pid; exit' SIGQUIT
done
