#!/usr/bin/env bash
# Enable ngnix to be used by nginx user, and change by that user
pkill apache2
chown nginx:nginx /etc/nginx/
chmod 744 /etc/nginx/nginx.conf
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
sudo -u nginx service nginx restart
