#!/usr/bin/env bash
# Enable ngnix to be used by nginx user, and change by that user
pkill apache2
chown nginx: /etc/nginx/nginx.conf
chmod 744 /etc/nginx/nginx.conf
sudo -u nginx service nginx restart